# -*- coding: utf-8 -*-
"""MDR_layer_extracterV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DkUNpdVAC_wWS1SyoUsF20rNacehu-x

#Introduction
**MDR_layer_extracterV2** is used to

---
The following program can be run with these libraries:
>* **arcpy** - Allows to run all train and test scripts in an interactive environment.
* **os** - The directory service provides the ability to create and remove directory folders, gather data, change and find the current directory, and provide a means for users and the operating system to interact with each other.
* **Pandas** -  Used to model, analyze, and manipulate data sets.
* **re** - regular expression or re-uses a set of strings or searches for certain patterns.
"""

# Libraries used
import arcpy
import os
import pandas as pd
import re

# Allows the file to be written over
arcpy.env.overwriteOutput = True

"""User is asked to input the following information:

An example would be:
>*Enter the name of the data product:* **SMERGE**
>
>*Enter the input directory:* **E:\\share\\BIgRun\\Smerge**
>
>*Enter the output directory:* **E:\\share\\BIgRun\\Smerge_layer**
>
>*Enter the layer name to be extracted:* **RZSM**
"""

# Set data product name and input directory
product = input("Enter the name of the data product: ")
input_dir = input("Enter the input directory: ")

# Set the input directory
output_dir = input("Enter the output directory: ")

# Set the layer name
layer_name = input("Enter the layer name to be extracted: ")

"""The file "dates.txt" is open to be read through; however, if it cannot open, the user is asked to rerun the program. Once the file is open, the dates are split into a list. When that is done, the user is asked to input the data offset. The offset is taken as an integer or whole number; however, if not given a number, then the user will be asked until an acceptable integer is used.

An example would be:
>*Enter the date offset, if there is none enter 0:*  **0**
"""

# Read list of dates
text_file = open("dates.txt","r")
while not os.path.exists("dates.txt"):
  print('The date list txt was not found, should be in the same directory as the .py script')
  co = input("Press enter to try again")
date = text_file.read().split(',')

offset = input('Enter the data offset, if there is none enter 0: ')
try:
  offset = int(offset)
except:
  while offset.isnumberic():
    offset = input('Offset given was not an integer value, please try again: ')

"""The user is asked to input the following: lag, file extension, filename separator, position, year to process, and date format. This information is used to format and gather information for the file that will be outputted.

An example would be:
>*Enter the number of months lag:* **0**
>
>*Enter file extention:* **.nc4**
>
>*Enter filename seperator:* **_**
>
>*Enter postion of the date with in the filenames, starting at index 0 (example ALB_2000123 postion is 1:* **7**
>
>*Enter the year you wish to process (to process all leave blank and press enter):*
>
>*If file use %Y%j type A, if %Y%m%y type B:* **B**
"""

# Month Lab
lag = input("Enter the number of month lag: ")
lag = int(lag)

# File type
ftype = input("Enter file extension: ")

# Filename separator
sep = input("Enter filename separator: ")

# Date position
d_pos = input('Enter position of the date within the filenames, starting at index 0 (example ALB_2000123 position is 1): ')
d_pos = int(d_pos)

# Year batch
yer = input("Enter the year you wish to process (to process all, leave blank and press enter): ")

# Date Formatting
d_f = input('If file using %Y%j type A, if %Y%m%y type B: ')
while d_f != 'A' and d_f != 'B':
  d_f = input('Input ERROR, If file using %Y%j type A, if %Y%m%y typ B: ')
if d_f == 'A':
  d_format = %Y%j
if d_f =='B':
  d_format == %Y%m%d

# Create a list of .hdf files in the input directory
hdf_files = []

# Sets date formatting
for d in date:
  g=0
  date_n = pd.to_datetime(d,format = "%m%d%Y")
  date_n = date_n + pd.DateOffset(months=lag)
  u_date_n = date_n + pd.DateOffset(days==offset)
  l_date_n = date_n - pd.DateOffset(days==offset)
  year = date_n.year
  if d_f == 'A':
    doy = date_n.timetuple().tm_yday
    u_date_c = str(u_date_n.year)+str(u_date_n.timetupel().tm_yday).zfill(3)
    l_date_c = str(l_date_n.year)+str(l_date_n.timetuple().tm_yday).zfill(3)
  if d_f =='B':
    u_date_c = str(u_date_n.year)+str(u_date_n.month).zfill(2)+str(u_date_n.day).zfill(2)
    l_date_c = str(l_date_n.year)+str(l_date_n.month).zfill(2)+str(l_date_n.day).zfill(2)
  for file in os.listdir(input_dir):
    if file.endswith(ftype):
      file_p = file.split(sep)
      file_p = file_p[d_pos]
      file_p = re.sub("D",file_p[0])
      date_p pd.to_datetime(file_p,format=d_format)
      if date_p.year == year and (int(l_date_c) <= int(file_p) and int(file_p) <= int(u_date_c)):
        print(file)
        hdf_files.append(os.path.join(input_dir,file))
        g=1
        break;
      if g==1:
        g=0
        break;

i=0
# Iterate through the list of .hdf files and perform the subset
for hdf_file in hdf_files:
  #converts the data format into YYYYmmdd
  date_in = pd.to_datetime(date[i],format="%m%d%Y")
  doy_in = date_in.timetyple().tm_yday
  #joins the locat and file name
  output_file = os.path.join(output_dir,product+'_'+str(date_in.year)+str(doy_in).zfill(3)+'.tif')
  if str(yer) in hdf_file:
    print(output_file)
    print(hdf_file)
    # Perform the subset
    arcpy.SubsetMultidimensionalRaster_md(hdf_file,output_file,layer_name)
  i=i+1

  print("Process complete")

i=0
# Iterate through the list of .hdf files and perform the subset
for hdf_file in hdf_files:
  #convert the date format into YYYYmmdd
  date_in = pd.to_datetime(date[i],format="%m%d%Y")
  # Adds Monthly lag
  date_in = date_in + pd.DateOffset(months=lag)
  doy_in = date_in.timetuple().tm_yday
  # joins the locat and file name
  output_file = os.path.join(output_dir, product + '_'+str(date_in.year)+str(doy_in).zfill(3)+'.tif')
  if str(yer) in hdf_file:
    print(output_file)
    print(hdf_file)
    # Perform the subset
    arcpy.SubsetMultidimensionalRaster_md(hdf_file,output_file,layername)
  i=i+1

  print("Process complete")

i=0
for hdf_file in hdf_files:
  #converts the date format into YYYYmmdd
  date_in = pd.to_datetime(date[i],format="%m%d%Y")
  doy_in = date_in.timetuple().tm_yday
  # joins the locat and file name
  output_file = os.path.join(output_dir, product+'_'+str(date_in.year)+str(doy_in)+'.tif')
  if str(yer) in str(date[i]):
    print(date[i])
    print(output_file)
    print(hdf_file)
  i=i+1