# -*- coding: utf-8 -*-
"""MultiBand_Raster_Extracter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1IgKz4qvKWr2UAzBArF62A9d5db-hae

# Introduction

The **MultiBand_Raster_Extractor** program enables the extraction of one or multiple bands, or the reordering of bands as a multiband raster layer. It facilitates the creation of a duplicate raster file as output.

---
The following libraries are imported to allow the code to be run:
- **os** - The directory service provides the ability to create and remove directory folders, gather data, change and find the current directory, and provide a means for users and the operating system to interact with each other.
- **sys** - Provides a way to manipulate the runtime of the program by using certain parameters and functions.
- **arcpy** - ArcPy enables efficient and effective geographic data analysis, data management, map automation, and data conversion. With ArcPy, users can leverage the capabilities of Python to effortlessly handle complex geospatial tasks.

---
> **Note:**
  - To ensure the code is tailored to the user's requirements, edit the comments so that they are included when running the script.
"""

import os
import sys
import arcpy

"""- The user will be asked to input the file path and name of the raster file.

  - An example of the file path would be the following:
> *Enter the full file path of the template point shape file:* **E:\\share\\MODIS_CONUS_NDVI\\CONUS_AQUA_C6_eMODIS_wkly_smNDVI_2015.tif**

  - An example of the raster file would be the following:
> *Enter the name of the raster file:* **CONUS_SQUA_C6_eMODIS_wkly_smNDVI_2015.tif**

- When the user provides the file path and name of the raster file, these elements are concatenated to create a new file named **raster_file**.
"""

# State the file path
raster_path = input("Enter the full file path of the template point shape file: ")

# State the name of the raster file
raster_name = input("Enter the name of the raster file: ")

# Creating a full path of the point shape file path and the name of the raster file
raster_file = os.path.join(raster_path, raster_name)

"""- The script first navigates to the directory containing the specified raster file, making it the current workspace.
- Subsequently, it generates a list of all raster datasets located within that workspace, providing a comprehensive overview of the available raster data.
- The files are then used with the CopyRaster function and the output with the new file name, including the band number.
"""

# Gets a list of the bands that make up the raster
arcpy.env.workspace = raster_file
bRng = arcpy.ListRasters()

for ThisBnd in bRng:
  # Loop through the bands and export each one with CopyRaster
  InBand = os.path.join(raster_file, ThisBnd)
  bndDesc = arcpy.Describe(InBand)
  NoData = bndDesc.noDataValue
  # Splits the image name and extension
  InSplit = os.path.splitext(raster_file)
  OutRas = '{}_{}{}'.format(InSplit[0], ThisBnd, InSplit[1])
  arcpy.CopyRaster_management(InBand, OutRas, nodata_value = NoData)