# -*- coding: utf-8 -*-
"""multiD_raster_merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rh4H55e9MHIAQcS-ryNsY85X8x6ObMI

# Introduction

The **multiD_rasters_merge** script merges multiple multidimensional raster datasets into a combined, single raster dataset.

---
The following libraries are imported to allow the code to be run:
- **os** - The directory service provides the ability to create and remove directory folders, gather data, change and find the current directory, and provide a means for users and the operating system to interact with each other.

- **re** - regular expression (or **re**) specifies a set of strings, where a particular string will match the given regular expression.
> For more information visit: https://docs.python.org/3/library/re.html

- **Pandas** - Is a tool for modeling, analyzing, and manipulating data sets.
> For more information visit: https://www.geeksforgeeks.org/introduction-to-pandas-in-python/#




*arcpy*

---
- **arcpy** - ArcPy enables efficient and effective geographic data analysis, data management, map automation, and data conversion. With ArcPy, users can leverage the capabilities of Python to effortlessly handle complex geospatial tasks.

- **env** - ArcPy environmental settings provide access to both general geoprocessing settings and the settings of a specific tool.

- **arcpy.sa** - The arcpy.sa module in Python facilitates the analysis of raster and vector data. It leverages the functionalities offered by the ArcGIS Spatial Analyst extension.

*datetime*

---

- **datetime** - The Python Datetime module provides classes for working with dates and times.

---

> **Note:**
  - To ensure the code is tailored to the user's requirements, edit the comments so that they are included when running the script.
"""

import os
import re
import pandas  as pd
import arcpy
from arcpy import env
from arcpy.sa import *
from datetime import datetime

"""- Provide the path to the parent folder and specify the name of the geodatabase. These variables will be concatenated to ensure a smooth execution of the code."""

# Define the parent folder and the geodatabase name
parent_folder = input('Enter the path to the parent folder: ')
geodatabase_name = input('Enter the name of the geodatabase: ')

# Create the file geodatabase
geodatabase_path = os.path.join(parent_folder, geodatabase_name)

"""> **Note**:
  - The following code plays a crucial role in generating the geodatabase, which serves as the working directory for the application. Hence, it should be retained in the code regardless of whether it is being utilized or not.
       arcpy.CreateFileGDB_management(parent_folder, geodatabase_name)
"""

## Generates the geodatabase (geodatabase is used as a working directory)
## Crucial to keep code as it is needed to run.

#arcpy.CreateFileGDB_management(parent_folder, geodatabase_name)

"""- **arcpy.env.workspace** establishes the geodatabase as the base workspace for all subsequent operations.

- Then, the program confirms the Spatial Analyst extension, which is a prerequisite for geoprocessing operations.

- Subsequently, the process of comparing multidimensional variables is disabled, which can occasionally enhance performance.

- Moreover, the program permits the overwriting of existing output files. This feature is particularly valuable when running a process repeatedly or when uploading data.
"""

# Set the geodatabase as the workspace
arcpy.env.workspace = geodatabase_path

# Set up the environment
arcpy.CheckOutExtension("Spatial")

arcpy.env.matchMultidimensionalVariable = False
#arcpy.env.cellSize = 200
arcpy.env.overwriteOutput = True
#input_dir = r"D:\LST\TXson_Rasters\New_folder"

"""- The user will then be asked to state the input directory and the ouput directory.

  - An example for the input directory would be the following:
>*Enter the input directory:* **E:\share\BIgRun\LAI\early**

  - An example for the output directory would be the following:
> *Enter the output directory:* **E:\share\BIgRun\LAI_Merged\A**
"""

# Set the input directory
input_dir = input("Enter the input directory: ")

# Set the output directory
output_dir = input("Enter the output directory: ")

"""- The user is requested to specify how many files are to be merged at the same time.
  - An example would be the following:
  > *Enter the number of files that need to be merged at a time:* **3**

- The variable **dir** utilizes a function to obtain a directory of all files and directories contained within the **input_dir**.

- To determine the total number of files, the program subtracts 1 from the length of the variable **dir** because **dir** includes both the current directory and the actual files. Since the current directory is not a file, it is excluded from the count.

- Finally, the program concludes by displaying the value stored in the variable **total_files**, which represents the total number of files in the directory.
"""

# State the amount of files that will be merged at a time.
file_n = input("Enter the number of files that need to be merged at a time: ")

# Get a list of all files and directories in input_dir
dir = os.listdir(input_dir)

# Subtracts 1 from the length of the list
total_files = len(dir) - 1

# Prints out the value of total_files
print(total_files)

"""- A while-loop is employed to iterate over files as long as the variable *i* is less than the total number of files, **total_files**.

  If the value of *i* exceeds 646, the following steps are executed:
  - The *i*th element of the variable **dir** will be split using a "." character as the delimiter and the element will be saved in **file_p1**.
  
  - The non-digits are eliminated from the second element of **file_p1** using a regular expression, and the outcome is kept in **file_d1**.
  - The value of *i* is printed.
  - The variable **f_inputs** is assigned an empty list.
  - As the code loops through the range specified by *int(file_n)*, the code iterates over *j*. Then it constructs a file path by combining the path to the file **dir[i + j]** with the input directory **input_dir**. This file path is appended to the **f_inputs** list.
  - The list of input files named **f_inputs** will be printed.
  - The output file path, denoted as **f_out**, is constructed by combining the **output_dir** with the first and second elements of **file_p1** using an underscore separator. The resulting path is then supplemented with a '.crf' extension.
  - The *MergeMultidimensionalRasters* function merges the raster files listed in **f_inputs** into a single multidimensional raster file at the path **f_out**. When pixels from the input rasters overlap, the *MEAN* argument dictates that the mean value should be employed.

  Finally, the value of *i* is increased by 2 until total_files is completed.
"""

i = 0
k = 4
print(i)
while i < total_files:
    if i > 646:
        file_p1 = dir[i].split('.')
        file_d1 = re.sub("\D", "", file_p1[1])
        print(i)
        f_inputs = []
        for j in range(int(file_n)):
            f_inputs.append(os.path.join(input_dir, dir[i + j]))
        # f1 = os.path.join(input_dir,dir[i])
        # f2 = os.path.join(input_dir,dir[i+1])
        print(f_inputs)
        f_out = os.path.join(output_dir, file_p1[0] + '_' + file_p1[1] + '.crf')
        arcpy.md.MergeMultidimensionalRasters(f_inputs, f_out, 'MEAN')
    i = i + 2